---
title: "Relationship Between Black-Throated Blue Warbler Characteristics and Mass"
author: "Jenna Wisniewski"
date: "12/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(GGally)
library(stargazer)
library(broom)
library(kableExtra)
library(naniar)
```

```{r}
## read in the data
warblers <- read_csv(here("exam_data","bt_warblers.csv"))

## convert all of the missing values stored as -99.99 to N/A
warblers_new <- warblers %>% 
  replace_with_na_all(condition =~.x == -99.99 )

```

```{r}
## create an exploratory ggplot of wing length vs. bird mass among different age groups with point color indicating sex and faceted by bird age at capture
ggplot(data = warblers_new, 
       aes(x = mass, y = wing_r)) + 
  geom_point(size = 2, aes(color = sex)) + 
  theme_bw() +
  facet_wrap(~ age_banded) + 
  labs(x = "Mass (grams)",
      y = "Right Wing Length (mm)", # FIXED
       title = "Relationship Between Black Throated Blue Warbler Wing Length and Mass Across Age Groups") 

```
```{r}
## create an exploratory ggplot of wing length vs. bird mass at different elevation levels with point color indicating sex and faceted by elevation of the sample plot
ggplot(data = warblers_new, 
       aes(x = mass, y = wing_r)) + 
  geom_point(size = 2, aes(color = sex)) + 
  theme_bw() +
  facet_wrap(~ elevation) + 
  labs(x = "Mass (grams)",
      y = "Right Wing Length (mm)", # FIXED
       title = "Relationship Between Black Throated Blue Warbler Wing Length and Mass Across Age Groups") 
```
```{r}
## create an exploratory ggplot of bill depth vs. bill culmen among different age groups with point color indicating sex and faceted by elevation of the sample plot
ggplot(data = warblers_new, 
       aes(x = bill_culmen, y = bill_depth)) + 
  geom_point(size = 2, aes(color = sex)) + 
  theme_bw() +
  facet_wrap(~ age_banded) + 
  labs(x = "Culmen Length (mm)",
      y = "Bill Depth (mm)", # FIXED
       title = "Relationship Between Black Throated Blue Warbler Culmen Length and Bill Depth Across Age Groups") 
```
```{r}
## Create a multiple linear regression model that describes the relationship between bird mass and wing length

##start by exploring the relationship between all variables using pair plots in GGally
warblers_new %>% 
  select(sex, bill_depth:wing_r) %>% 
  ggpairs (aes(color =sex))



```
```{r}
## create multiple linear regression models in order to determine which variables yield the best fit 

lm1 <- lm(mass ~ wing_r +sex, data = warblers_new)

lm2 <- lm(mass ~ wing_r +sex +elevation, data = warblers_new)

lm3 <- lm(mass ~ wing_r +sex +elevation +age_banded, data = warblers_new)

lm4 <- lm(mass ~ wing_r +sex +elevation +age_banded + bill_depth, data = warblers_new)

lm5 <- lm(mass ~ wing_r +sex +elevation +age_banded + bill_depth + tarsus1, data = warblers_new)

lm6 <- lm(mass ~ wing_r +elevation +age_banded + bill_depth + tarsus1, data = warblers_new)

lm7 <- lm(mass ~ wing_r +sex +age_banded + bill_depth + tarsus1, data = warblers_new)

lm8 <- lm(mass ~ wing_r +sex + bill_depth + tarsus1, data = warblers_new)

lm9 <- lm(mass ~ wing_r +sex + elevation +bill_depth + tarsus1, data = warblers_new)

## Find the AIC for each model to compare and choose the lowest
AIC(lm1)
AIC(lm2)
AIC(lm3)
AIC(lm4)
AIC(lm5) 
AIC(lm7)
AIC(lm8)
AIC(lm9) ## lowest value
```

```{r, results = 'asis'}
## use stargazer to show the multiple linear regression coefficients for ln9
stargazer(lm9, type = "html")
```

